### ISSUE TITLE
need conda-forge channel

### ISSUE THREAD

**Issue by bregeon** [gammasim/telescope-layouts#2]
```
[bregeon@lpsc1224x telescope-layouts]$ conda env create -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - yamllint
```

Is fixed with:
`conda config --add channels conda-forge
`
may be that can be specified in the `environment.yml`, I don't know.

**Comment by GernotMaier** [comment]
yamllint is not needed (was for the development). I removed it from the environment file with commit cac8d55
